version: "3.6"
services:
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - shared
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
    ports:
      -  8082:8081
      - 18081:18080
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - shared
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
    ports:
      - 8083:8081
      - 18082:18080
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - shared
    depends_on:
      - spark-master

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
networks:
  shared:
    external: true